---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: veridex
  source:
    repoURL: https://github.com/caribrefresh-source/Veridex-Platform.git
    targetRevision: main
    path: kubernetes/cluster/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
