---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-system
  annotations:
    veridex.io/owner: platform-data
    veridex.io/purpose: CloudNativePG operator control plane
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    veridex.io/wave: "6"
    veridex.io/role: database-operator
    veridex.io/lifecycle: planned
    veridex.io/recovery-class: reconcile
    veridex.io/data-classification: internal

